### ISSUE TITLE
Paper

### ISSUE THREAD

**Issue by iosonosempreio** [jkaupp/DHQ#1]
Hello,
I'm a design student writing a thesis on DH and I'd like to cite your work. I downloaded the related paper, but I can't find any reference to a publication date. Could you confirm me it was this year (2015)?
Thanks

Tommaso

**Comment by jkaupp** [comment]
Hello,

The paper was written for the most recent offering of IVMOOC and was indeed in
2015.

Please be sure to cite all authors accordingly.

Best,

Jake Kaupp

On Tue, May 26, 2015 at 11:18 AM, iosonosempreio < notifications@github.com [notifications@github.com] > wrote:
Hello,
I'm a design student writing a thesis on DH and I'd like to cite your work. I
downloaded the related paper, but I can't find any reference to a publication
date. Could you confirm me it was this year (2015)?
Thanks

Tommaso

**Comment by iosonosempreio** [comment]
Sure, many thanks.
T.
